news/urls.py
from django.urls import path
from .views import PostList, PostDetail, PostSearch, NewsPostCreate, NewsPostUpdate, NewsPostDelete, ArticlePostCreate, ArticlePostDelete, ArticlePostUpdate


urlpatterns = [
    path('', PostList.as_view(), name = 'posts'),
    path('<int:pk>', PostDetail.as_view(), name = 'post_detail'),
    path('search/', PostSearch.as_view(), name = 'search'),
    path('news/create/', NewsPostCreate.as_view(), name = 'news_post_create'),
    path('news/<int:pk>/update/', NewsPostUpdate.as_view(), name='news_post_update'),
    path('news/<int:pk>/delete/', NewsPostDelete.as_view(), name='news_post_delete'),
    path('article/create/', ArticlePostCreate.as_view(), name = 'article_post_create'),
    path('article/<int:pk>/update/', ArticlePostUpdate.as_view(), name='article_post_update'),
    path('article/<int:pk>/delete/', ArticlePostDelete.as_view(), name='article_post_delete'),
    path('article/<int:pk>/delete/', ArticlePostDelete.as_view(), name='article_post_delete')
]

newspaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns =[
    path('admin/', admin.site.urls),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('posts/', include('news.urls')),
    path('accounts/', include('allauth.urls'), name = 'accounts'),
    
]
    

news/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


# Create your models here.
class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    authorRating = models.IntegerField(default=0)

    def update_rating(self):

        author_posts_rating = Post.objects.filter(author_id=self.pk).aggregate(posts_rating_sum=Sum('postRating') * 3)['posts_rating_sum']
        
        authorCommentsRating = Comment.objects.filter(userPost_id=self.user).aggregate(comments_rating_sum=Sum('commentRating'))['comments_rating_sum']
        
        postCommentRating = Comment.objects.filter(commentPost_id=self.pk).aggregate(comments_post_rating_sum=Sum('commentRating'))['comments_post_rating_sum']

        self.authorRating = author_posts_rating + authorCommentsRating + postCommentRating
        self.save()
    
    
    def __str__(self):
        return f'{self.user}'


class Category(models.Model):
    categoryName = models.CharField(max_length=64, unique=True)
    
    
    def __str__(self):
        return f'{self.categoryName}'


class Post(models.Model):
    
    article = 'AR'
    news = 'NW'
    
    POST_TYPE = [
        (article, 'Статья'),
        (news, 'Новости')
    ]
    
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    postType = models.CharField(max_length=2, choices=POST_TYPE, default=article)
    timeDateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through="PostCategory")
    title = models.CharField(max_length=255)
    text = models.TextField()
    postRating = models.IntegerField(default=0)


    def like(self):
        self.rating += 1
        self.save()    
    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:128] + '...'
    
    def __str__(self):
        return f'{self.author}, {self.timeDateCreation}, {self.title}'
    
    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])
    
    
    

class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.post}, {self.category}'

class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    userPost = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    creationData = models.DateTimeField(auto_now_add=True)
    commentRating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    
    def dislike(self):
        self.rating -= 1
        self.save()

templates/article_post_create.html
{% extends 'flatpages/default.html' %}

{% block content %}

<h1>Добавлить статью</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save"/>
</form>
{% endblock content %}

templates/article_post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title}}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/article_post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}

<h1>Редактирование статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save"/>
</form>
{% endblock content %}

templates/main.html
<html>
    <head>
        <title> Newspaper</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/news_post_create.html
{% extends 'flatpages/default.html' %}

{% block content %}

<h1>Добавить новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save"/>
</form>
{% endblock content %}

templates/news_post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удалить новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/news_post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}

<h1>Редактирование новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save"/>
</form>
{% endblock content %}

templates/post.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
    News
{% endblock title %}

{% block content %}
    <h1>Все новости</h1>
    <h2>{% current_time '%b %d %Y' %}</h2>
    <div>{{posts_link | length}}</div>
    <hr>
    {% if posts_link %}
        {% for post in posts_link %}

            <h2>{{ post.title }}</h2>
            <div>
                {{ post.timeDateCreation }}
            </div>
            <div>
                {{ post.text|truncatewords:20|censor}}
                

            </div>
            <div>
                Автор: {{ post.author }}, Рейтинг: {{ post.postRating }}, Категория: 
                {% for cat in post.postcategory_set.all %}
                    {{ cat.category }}
                {% endfor %} Тип поста: {{ post.postType }} id:{{post.pk}} 
                <a href="{{ post.pk }}">Читать далее</a>
            </div>
                
        {% endfor %}

    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}
    {# Добавляем пагинацию на страницу #}

    {# Информация о предыдущих страницах #}
    {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {# Информация о текущей странице #}
    {{ page_obj.number }}

    {# Информация о следующих страницах #}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
{% endblock content %}

templates/post_detail.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Post detail
{% endblock title %}


{% block content %}
{% if post_link %}
<h1>{{ post_link.title }}</h1>
<div>
  {{ post_link.timeDateCreation }}
</div>
<div>
  {{ post_link.text|censor }}
</div>
<div>
  Автор: {{ post_link.author }}, Рейтинг: {{ post_link.postRating }}, Категория: 
  {% for cat in post_link.postcategory_set.all %}
      {{ cat.category }}
  {% endfor %}
</div>
{% else %}
<h2>Новостей нет!</h2>
{% endif %}
{% endblock content %}\